apiVersion: v1
kind: Service
metadata:
  name: messages-service
spec:
  selector:
    app: messages-service
  ports:
    - protocol: TCP
      port: 80 # Cluster-wide port
      targetPort: 8083 # The container's port
  type: ClusterIP
