apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database-container
          image: johanes406/custom-mysql:latest # Use your pushed image
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Bashartt123" # Ensure this matches your database configuration
            - name: MYSQL_DATABASE
              value: "microservicestestKubernetes"
