# Base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the application files, including .env
COPY . .

# Ensure the uploads directory exists with proper permissions
RUN mkdir -p /app/uploads && chmod -R 777 /app/uploads

# Expose the application port
EXPOSE 8085

# Start the application
CMD ["node", "app.js"]
