apiVersion: v1
kind: Service
metadata:
  name: journalfrontend-service
spec:
  selector:
    app: journalfrontend
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service
      targetPort: 3000  # Port where the app listens inside the container
  type: ClusterIP       # Use ClusterIP instead of NodePort