# Use a base image with JDK 17 (slim variant for smaller size)
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the built JAR file from the build image
COPY target/quarkussearch-1.0.0-SNAPSHOT-runner.jar app.jar

# Expose the port the application will run on
EXPOSE 8084

# Run the application
CMD ["java", "-jar", "app.jar"]


