apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  selector:
    app: image-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30085 # Specify a NodePort
  type: NodePort
