apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/images" # Path on the Kubernetes node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
