apiVersion: v1
kind: Service
metadata:
  name: journal-service
spec:
  selector:
    app: journal-service
  ports:
    - protocol: TCP
      port: 8081 # Cluster-wide port
      targetPort: 8081 # The container's port
  type: ClusterIP # Exposes the service within the cluster only
