apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 80 # Cluster-wide port
      targetPort: 8082 # The container's port
  type: ClusterIP
