apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082 # Cluster-wide port
      targetPort: 8082 # The container's port
  type: ClusterIP
